export interface SPE_DESPATCH_ITEM {
  tipoDocumentoRemision?: string | null;
  numeroDocumentoRemision?: string | null;
  serieNumeroGuia?: string | null;
  tipoDocumentoGuia?: string | null;
  numeroOrdenItem?: string | null;
  cantidad?: string | null;
  unidadMedida?: string | null;
  descripcion?: string | null;
  codigo?: string | null;
  codigoProductoSUNAT?: string | null;
  bl_createdAt?: string | null;
  codigoProductoGS1?: string | null;
  codigoLeyenda_1?: string | null;
  textoLeyenda_1?: string | null;
  codigoLeyenda_2?: string | null;
  textoLeyenda_2?: string | null;
  codigoLeyenda_3?: string | null;
  textoLeyenda_3?: string | null;
  codigoLeyenda_4?: string | null;
  textoLeyenda_4?: string | null;
  codigoLeyenda_5?: string | null;
  textoLeyenda_5?: string | null;
}
